# Set Name Project
spring:
    application:
        name: EPR FE

  # * default Get & Post => enable HttpMethod other
    mvc:
        hiddenmethod:
            filter:
                enabled: true


# Set Port
server:
    port: 9009
# * get endpoint
    base:
        url: http://localhost:9005